export const USERNAME = 'username'
export const USERTYPE = 'userType'
export const USERID = 'userId'
export const TOKEN = 'token'
export const REFRESH_TOKEN = 'refresh_token'
export const AUTHORIZATION = 'Authorization'
export const USERINFO = 'userInfo'